# Generated by Django 2.2 on 2022-06-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_farmerscropdatamodels_farmerscropsmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerscropdatamodels',
            name='cdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
