# Generated by Django 2.2 on 2022-06-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_auto_20220630_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerscropsmodels',
            name='cdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
